spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  sql:
    init:
      mode: embedded
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.H2Dialect
        highlight_sql: true
        format_sql: true
        show_sql: true
        use_sql_comments: true
      open-in-view: false
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      password:
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
    mongodb:
      uri: ${MONGO_DB_URI}
  file:
    base-dir: ${FILE_BASE_DIR}
    img-dir: ${FILE_IMG_DIR}

#logging:
#  level:z
#    org.mongodb.driver.client: warn
#    org.mongodb.driver.cluster: warn

#    org.hibernate.sql: debug
#    org.hibernate.type: trace